services:
  db:
    image: postgis/postgis:15-3.3-alpine
    container_name: geo_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourstrongpassword
      POSTGRES_DB: test_kare
    ports:
      - "5432:5432"
    healthcheck:
      # pg_isready is a built-in tool to check if the DB is up
      test: ["CMD-SHELL", "pg_isready -U postgres -d test_kare"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: dockerfile  # Explicitly point to your lowercase file
    container_name: geo_backend
    environment:
      POSTGRES_HOST: db   # This is the 'db' service name above
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: test_kare
    depends_on:
      db:
        condition: service_healthy # Backend starts ONLY after db passes healthcheck

  frontend:
    build: ./frontend
    container_name: geo_frontend
    ports:
      - "5173:5173"
    environment:
      VITE_BACKEND_URL: http://localhost:5000
    depends_on:
      - backend
