services:
  db:
    image: postgis/postgis:15-3.3-alpine
    container_name: geo_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourstrongpassword
      POSTGRES_DB: test_kare
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: geo_backend
    ports:
      - "5000:5000"
    environment:
      POSTGRES_HOST: db # Use service name instead of host.docker.internal
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourstrongpassword
      POSTGRES_DB: test_kare
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build: ./frontend
    container_name: geo_frontend
    ports:
      - "5173:5173"
    environment:
      VITE_BACKEND_URL: http://localhost:5000
    depends_on:
      - backend
